
import Header from "@/components/Header";
import "./globals.scss"
import { Providers } from "../../frontend/providers";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Flight Gyani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
